[package]
name = "fbtoggl"
version = "0.1.0"
edition = "2021"
authors = ["Stefan Ruzitschka <stefan@icepuma.dev>"]
description = "Terminal client to interact with toggl.com REST api."

[dependencies]
clap = { version = "3.0.0-beta.5", features = [
    "suggestions",
    "color",
    "env",
    "unicode",
] }
clap_generate = "3.0.0-beta.5"
reqwest = { version = "0", features = ["blocking", "json"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0", features = ["serde"] }
xdg = "2"
config = "0"
toml = "0"
dialoguer = "0"
openssl = { version = "0.10", features = ["vendored"] }
mockito = "0"

[dev-dependencies]
env_logger = "0"
ctor = "0"
pretty_assertions = "1"
