[package]
name = "fbtoggl"
version = "0.5.10"
edition = "2021"
authors = ["Stefan Ruzitschka <stefan@icepuma.dev>"]
description = "Terminal client to interact with track.toggl.com REST api."
keywords = ["toggl", "track", "time-tracking", "cli", "productivity"]
repository = "https://github.com/icepuma/fbtoggl"
readme = "README.md"
license = "WTFPL"

[dependencies]
clap = { version = "3", features = [
    "derive",
    "suggestions",
    "color",
    "env",
    "unicode",
    "wrap_help"
] }
reqwest = { version = "0", features = ["blocking", "json"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0", features = ["serde", "clock"] }
now = "0"
xdg = "2"
config = "0"
toml = "0"
dialoguer = "0"
openssl = { version = "0.10", features = ["vendored"] }
mockito = "0"
urlencoding = "2"
jackdauer = "0"
term-table = "1"
colored = "2"
hhmmss = "0.1"
itertools = "0"
htp = "0"

[dev-dependencies]
env_logger = "0"
ctor = "0"
pretty_assertions = "1"
