on:
  push:
    tags:
      - "v*"
name: Release
jobs:
  build:
    name: crates.io Release
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: fbtoggl
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      #- run: cargo login ${CARGO_RELEASE_TOKEN}
      #  env:
      #    CARGO_RELEASE_TOKEN: ${{ secrets.CARGO_RELEASE_TOKEN }}
      #- run: cargo publish
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: cargo build --release
